### ISSUE TITLE
Named Parameters With Multiple Types don't appear in documentation

### ISSUE THREAD

**Issue by sparkpunkd** [raml2html/raml2html#146]
raml2html version: 2.0.2

The RAML 0.8 spec says that "... the value of the named parameter property MAY be an array of mappings ...", with a named parameter defined as "URI parameters, query string parameters, form parameters, request bodies (depending on the media type), and request and response headers".

I can define a named parameter to have multiple types but it does not appear in the generated HTML. Instead, the output is replaced by `()`. I can see that the `lib/item.numjuck` and `lib/resource.numjuck` are not set up to process an item of array type.

Example RAML input:

```
#%RAML 0.8
title: Testing multiple types for named parameters.

/testResource:
  get:
    queryParameters:
      name:
        - type: string
          description: I am a string type query parameter.
        - type: integer
          description: I am an integer type query parameter, which is an alternative option.
```

Fragment of generated HTML:

```
<h3>Query Parameters</h3><ul><li><strong>name</strong>: <em>()</em></li></ul>
```
