### ISSUE TITLE
raml2html version > 2.2.0: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by raafael911** [raml2html/raml2html#198]
I encountered the issue discussed in #160 so I updated my raml2html from 2.2.0 to 2.4.0 to see if the problem got fixed. Now I'm getting the following error when using raml2html:

```
[Error: Error: EISDIR: illegal operation on a directory, read]
```

When I go back to version 2.2.0 the tool works again, but I still can not see the details of my security description.
Btw: I encounter the same error on version 2.3.0.

Any help would be appreciated.

**Comment by ducin** [comment]
@raafael911 could you paste your raml somewhere? Or obfuscate and paste, so that we can reproduce the error?

**Comment by raafael911** [comment]
Sure. This is one of the smaller RAML files I am trying to generate documentation from. There are bigger ones but they all produce the same error:

```
#%RAML 0.8
---
title: Example REST interface
baseUri: http://Host/rest/
mediaType: application/json
documentation:
    - title: Dates
      content: !include Dates-Doc.md

schemas:
    - Session: !include schemas/REST-Admin-API/Session.json
    - Sessions: !include schemas/REST-Admin-API/Sessions.json
    - User: !include schemas/REST-Admin-API/User.json
    - Users: !include schemas/REST-Admin-API/Users.json

resourceTypes:
    - collection: !include resourceTypes/collection.yaml
    - collection-item: !include resourceTypes/collection-item.yaml

securitySchemes:
    - session-cookie: !include securitySchemes/session-cookie.yml

/Users:
    type: collection
    /{user_ID}:
        type: collection-item
        delete:
            securedBy: [session-cookie]

/Sessions:
    type: collection
    post:
        description: Login
    get:
    /{session_ID}:
        type: collection-item
```
