### ISSUE TITLE
Included DataType don't retain their name

### ISSUE THREAD

**Issue by ddidier** [raml2html/raml2html#270]
I've dumped `ramlObj` and I found that included DataTypes don't retain their name. I don't know if this is an issue in `raml2obj` or in the RAML parser that this librairy is using. I understand they are treated like anonymous types, but for example their name is retained in the API Console in the _Types_ section, and I think this is the way to go.

``` yaml
types:
  MyObject: !include dataTypes/MyObject.raml
body:
  type: MyObject
```

gives

``` json
"body": [
{
  "name": "MyObject",
  "displayName": "MyObject",
  "type": "object",
```

and

``` yaml
body:
  type: !include dataTypes/MyObject.raml
```

gives

``` json
"body": [
{
  "type": {
  "name": "type",
  "displayName": "type",
  "type": [
    "object"
  ],
```
