### ISSUE TITLE
Show nested dataType

### ISSUE THREAD

**Issue by rendau** [raml2html/raml2html#274]
In Raml 1.0:
 ```
types:
  user:
    type: object
    properties:
      id: integer
      name: string
  car:
    type: object
    properties:
      id: integer
      user: user
```

Then "car" shows like this:
```
  id: required integer
  user: required object
```

**object** says nothing, please expand nested data-types.
