### ISSUE TITLE
Item example shown before its properties

### ISSUE THREAD

**Issue by sluchznak** [raml2html/raml2html#295]
Hello. It's normal behavior?
![image](https://cloud.githubusercontent.com/assets/4091442/21227696/3cec12aa-c305-11e6-838e-e75ff18aa079.png)

raml:
```yml
types:
    Country:
        type: object
        properties:
            id: integer
            name: string
        example:
          id: 1
          name: "Russian Federation"
    City:
        type: object
        properties:
            id: integer
            name: string
            country_id: integer
            country?: Country
        example:
          id: 1
          name: "Moscow"
          country_id: 1
          country:
              id: 1
              name: "Russian Federation"
```
