### ISSUE TITLE
You can't seem to override a type's description

### ISSUE THREAD

**Issue by gwkunze** [raml2html/raml2html#298]
With the following simple RAML spec:

```
#%RAML 1.0
title: Test app
types:
  myIdType:
    type: string
    description: Some generic id type
/foo/{id}:
  uriParameters:
    id:
      type: myIdType
      description: My specific description overriding the generic description for myIdType
  get:
```

You'd expect the description of `id` in `/foo/{id}` to be the specific one, but you get:

![screen shot 2016-12-19 at 13 43 40](https://cloud.githubusercontent.com/assets/196545/21313292/41b02364-c5f1-11e6-8950-0311b7122337.png)
