### ISSUE TITLE
securedBy scopes support

### ISSUE THREAD

**Issue by scadams** [raml2html/raml2html#306]
With raml2html 4.0.5, I cannot seem to add `scopes`.

Given the following basic RAML:
```
#%RAML 1.0
title: Test API
baseUri: https://test
securitySchemes:
  custom_scheme:
    type: x-custom
/test:
  get:
    securedBy: [custom_scheme: { scopes: [ ADMINISTRATOR ] } ]
```

This is the output after running `raml2html test.raml`:
```
{
  "parserErrors": [
    {
      "code": "UNKNOWN_NODE",
      "message": "Unknown node: 'scopes'",
      "path": "test.raml"
  ]
}
```

I apologize if this isn't a raml2html issue. I've tried exploring some of the dependencies but can't determine where this error is coming from.
