### ISSUE TITLE
queryParameters in securitySchemes not rendered

### ISSUE THREAD

**Issue by andreasfrisch** [raml2html/raml2html#307]
We have the following at the top level of our .raml file.

```
securitySchemes:
  auth:
    type: Pass Through
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid auth token by setting value to "Bearer {accessToken}". {accessToken} is returned upon creation or login. Do not use together with the "accessToken" query parameter.
      queryParameters:
        accessToken:
          description: Used to send a valid auth token. Use only with GET requests. Do not use together with the "Authorization" header
```

Using raml2html 4.0.5 the 'security' tab of routes marked with 'securedBy: [auth]' does not contain the queryParameters information. It only contains the headers information.

![screen shot 2017-01-19 at 13 13 32](https://cloud.githubusercontent.com/assets/177252/22106544/684a29f0-de49-11e6-8eee-c5857369ac03.png)
