### ISSUE TITLE
Property of union type causes usage of the type to be mis-documented

### ISSUE THREAD

**Issue by murphyke** [raml2html/raml2html#319]
Given an object type `Thingy` containing a union type property, then if a URI parameter is of type `Thingy`, the parameter is not properly documented.  See the possibly related #314. Also, the related PR #317 doesn't fix my issue (unless I'm mistaken).

```yaml
#%RAML 1.0
title: Bug
types:
  Thingy:
    type: object
    properties:
      pk:
        type: integer
      value:
        type: string | number
/test:
  /{param}/:
    uriParameters:
      param:
        type: Thingy
    get:
```

If `Thingy`.`value` is of type `string | number` as shown, then the HTML documentation claims the `param` parameter to be of type `union`:

```
URI Parameters
    param: required (union)
```

On the other hand, if `Thingy`.`value` is a simple type, then it behaves as you would expect:

```
URI Parameters
    param: required (object)
        pk: required (integer)
        value: required (string)
```

Aside: the `API Designer` handles this situation correctly.  Hopefully someday `raml2html` could share code with `API Designer` and be accessible from it.
