### ISSUE TITLE
Various array- and inheritance-related issues

### ISSUE THREAD

**Issue by angelo-romano** [raml2html/raml2html#328]
Hi all,
I am struggling quite a bit with the tool lately due to a number of bugs. Apart from #323 , I am also having related issues with inheritance when dealing with types containing properties who are arrays. Example:

api.raml
```
types:
  BaseType: !include ./types/BaseType.raml
  AddedFields: !include ./types/AddedFields.raml
  FullType: [ BaseType, AddedFields]

/api/do-sthg:
    body:
      application/json:
        type: FullType
  
```

./types/BaseType.raml
```
#%RAML 1.0 DataType
properties:
  title:
    description: The title.
    required: true
    type: string
  someStructList:
    description: Struct list.
    required: true
    type: array
    items: !include ./Struct.raml
  someEnumList:
    description: Enum list.
    required: true
    type: array
    items:
        type: string
        enum: ["val1", "val2", "val3"]
```

./types/Struct.raml
```
#%RAML 1.0 DataType
properties:
  id:
    type: integer
    required: true
    description: An ID.
```
By doing this, no matter what: 1) the class returned as a response will not be fully composed, and it will be made up by only the fields that are in BaseType, unless I remove the two array-based fields. 2) the property composition in `someStructList` is never being rendered, as well as the enum choices in the `someEnumList`.

[This is an example, namely]
