### ISSUE TITLE
Types: Arrays getting not renderd

### ISSUE THREAD

**Issue by cebor** [raml2html/raml2html#332]
When defining an array in a type it only gets rendered in response/request with the implicit definition:

This does not work:
```yaml
MyType:
  type: object
  properties:
    myProp:
      type: array
      items: MyItems
```

This works:
```yaml
MyType:
  type: object
  properties:
    myProp: MyItems[]
```
