### ISSUE TITLE
datetime validator doesn't accept rfc3339 fractional seconds

### ISSUE THREAD

**Issue by lukeschlather** [raml2html/raml2html#338]
From my reading of the spec, fractional seconds can be represented with either a period or a comma after the smallest time increment. However, the following causes raml2html to complain that "Valid rfc3339 formatted string is expected." If you remove the fractional seconds (e.g. "2017-03-20T23:39:05+00:00") it works fine.

```yaml
#%RAML 1.0
title: Bad Datetime
types:
  Resource:
    type: object
    properties:
      created: datetime
    example: |
        {
            "created": "2017-03-20T23:39:05.651638+00:00"
        }
```
