### ISSUE TITLE
Properties in HTML do not appear in the same order as in the RAML source file

### ISSUE THREAD

**Issue by amammes** [raml2html/raml2html#358]
I am attaching sample raml and html files.

raml2html --version is 6.3.0
node --version is v6.11.0

[broken2.zip](https://github.com/raml2html/raml2html/files/1113011/broken2.zip)

**Comment by mikedeco** [comment]
Based on the raml using yaml syntax I attempted to put a hyphen in front of the properties. This seemed to maintain the order, but the results from raml2html lost the property names.

Example raml snippet:

```
properties:
  id:
    description: |
      The id.
    type: string
  name:
    description: |
      The name.
    type: string
  description:
    description: |
      The description.
    type: string
  startDate:
    description: |
      The start date.
    type: date-only
```

The above did not guarantee order but would display the names appropriately, something like the following:

**- description:** (string)
  The description.
**- name:** (string)
  The name.
**- id:** (integer)
  The id.
**- startDate:** (date-only)
  The start date.

When adding hyphens to the example snippet:

```
properties:
  - id:
    description: |
      The id.
    type: string
  - name:
    description: |
      The name.
    type: string
  - description:
    description: |
      The description.
    type: string
  - startDate:
    description: |
      The start date.
    type: date-only
```

order was maintained, but the property names lost:

**- :** (integer)
  The id.
**- :** (string)
  The name.
**- :** (string)
  The description.
**- :** (date-only)
  The start date.

I don't know whether the names being lost is a raml2obj or raml2html problem. But it does seem that ordering works it just breaks other things. I would love to look at this myself but my typescript/javascript skills are very lacking.
