### ISSUE TITLE
Rendering of inheriting type is wrong

### ISSUE THREAD

**Issue by arzonus** [raml2html/raml2html#363]
I have example types:
```
types:
  DeviceGroupInfo:
    properties:
      id: number
      name:
      platform_id: number
      parent_id: number

  DeviceInfo:
    properties:
      id: number
      name:
      platform_id: number
      group_id: number
      created: datetime
      updated: datetime
      connected: boolean
      monitoring: boolean
      time_zone:

  DeviceGroup:
    type: DeviceGroupInfo
    properties:
      groups?: DeviceGroup[]
      devices?: DeviceInfo[]
    
```

In html from raml2html:
![image](https://user-images.githubusercontent.com/4450829/29084133-beb90cd4-7c73-11e7-8ee0-ef995d7736a1.png)
In api-designer:
![image](https://user-images.githubusercontent.com/4450829/29084180-db4dbf02-7c73-11e7-86a4-be7cd409d8e5.png)

In api-designer I see, that DeviceGroup have array of DeviceGroup, but in html I see, DeviceGroup have array of DeviceGroupInfo and doesn't have properties of DeviceGroupInfo.
