### ISSUE TITLE
error on Cyclic dependency

### ISSUE THREAD

**Issue by stoffel2107** [raml2html/raml2html#384]
Hello,
when trying to create the html document of my raml file with:
`$ raml2html api.raml > api.html` it fails with the following warnings:
```
Warning: Unable to canonicalize type "Certificate": incompatible types: [$recur, $recur]
Warning: Unable to canonicalize type "Customer": incompatible types: [$recur, $recur]
Warning: Unable to canonicalize type "Repository": incompatible types: [$recur, $recur]
Warning: Unable to canonicalize type "Card": incompatible types: [$recur, $recur]
Maximum call stack size exceeded
```
The raml part which produces this error is the following:

```
Certificate:
  description: the certificate is the open unique id of business partner which is needed for the verification.
  type: object
  properties:
    id:
      type: integer
    certstat:
      type: Certstat
    expiryDate:
      type: integer
    content:
      type: string
    parentCert?:
      type: Certificate
```
As shown there is a Cyclic dependency (which is necessary for my api) at parentCert?: Certificate which causes the conversion to fail. 
I already opened and discussed this issue on raml-js-parser-2 but as the Contributor there showed in a post, the parser is indeed accepting and parsing this dependency without any problem. So is there a way to create that html document with the cyclic dependency ?

This is the issue at raml-js-parser-2 (https://github.com/raml-org/raml-js-parser-2/issues/812)

thanks for reading.
kind regards
Stoffel2107
