### ISSUE TITLE
Output incorrect from markdown

### ISSUE THREAD

**Issue by ArtFlag** [raml2html/raml2html#392]
Hi, 
I've encountered a Markdown issue:

RAML:
```
#%RAML 1.0
title: Authentication
version: v0
baseUri: 'https://whatever.com/v0'
mediaType: application/json
documentation:
  - title: Authentication
    content: |
      - this
        - that
```

The generated output does not nest the lists:
```
<ul>
<li>this</li>
<li>that</li>
</ul>
```
