### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Shadowell** [raml2html/raml2html#406]
```
#%RAML 1.0
title: YoevaInternal API
version: v1

protocols: HTTP
mediaType: application/json

uses:
  JarRequestType: resourceTypes/jarRequest.raml
  Jars: types/jars.raml
  JobRequestType: resourceTypes/jobRequest.raml
  Jobs: types/jobs.raml
  Commons: types/commons.raml

/jars:
  type:
    JarRequestType.Collection:
      jarGetResponseType: Jars.JarList
      jarGetResponseExample: !include examples/jar-get-response.json
  /{jarId}:
    type:
      JarRequestType.CollectionItem1:
        jarDeleteResponseType: Jars.JarDeleteResponseModel
        jarDeleteResponseExample: !include examples/jar-delete-response.json
    uriParameters:
      jarId: Commons.Id
    /run:
      type:
        JarRequestType.CollectionItem2:
          jarRunRequestType: Jars.JarRunRequestModel
          jarRunRequestExample: !include examples/jar-run-request.json
          jarRunResponseType: Jars.JarRunResponseModel
          jarRunResponseExample: !include examples/jar-run-response.json
  /upload:
    type:
      JarRequestType.CollectionItem3:
        jarUploadResponseType: Jars.JarUploadResponseModel
        jarUploadResponseExample: !include examples/jar-upload-response.json

/jobs:
  type:
    JobRequestType.Collection:
      jobGetResponseType: Jobs.Jobs
      jobGetResponseExample: !include examples/job-get-response.json
  /{jobId}:
    type:
      JobRequestType.CollectionItem:
        jobDetailGetResponseType: Jobs.JobDetail
        jobDetailGetResponseExample: !include examples/job-detail-get-response.json
        jobPatchResponseType: Jobs.JobPatchResponseModel
        jobPatchResponseExample: !include examples/job-patch-response.json
    uriParameters:
      jobId: Commons.Id
    get:
    patch:

```

This is main raml file above,.
I encountered the following error when I try to generate html file:
''E:\FlinkDev\noops\yoeva-apis\src\main\resources\source\yoeva\api\internal>raml2html --theme raml2html-markdown-theme YoevaInternalAPI.raml > YoevaInternalAPI.html
Cannot read property 'length' of null''

raml2html --version: 7.2.2
node --version : v10.13.0
