### ISSUE TITLE
Types properies are not generated for some types.

### ISSUE THREAD

**Issue by sirinn** [raml2html/raml2html#419]
Hello,

I have these two `types` in my project. And the properties in `Types` part of the html for the first one gets generated properly, but for the second not. I don't see any issue with it.

I'm using slate theme.

## generated properly for type `aaa`
```
aaa:
    description: xyz
    properties:
      last_sequence:
        type: number
        description: xyz
       instrument_code:
        type: Instrument
        description: xyz
      granularity:
        type: TimeGranularity
        description: xyz
```

## not generated properly for type `bbb`
```
bbb:
    properties: 
      order_id: string
      account_id: string
      amount:
        type: Amount
        description: xyz
 ```
