### ISSUE TITLE
Refer attributes of composed type definition

### ISSUE THREAD

**Issue by longtimeago** [raml2html/raml2html#425]
Not sure if the title is meaningful (feel free to rename it :))

Suppose we have a type `Book` declared as
```
type: object
properties:
  bookId: 
    type: StringId
    description: Book identifier
```

And a type `StringId`
```
type: string
description: UTF-8 string, max length 256 characters
```
Is there any way to merge descriptions from `bookId` in Book and `StringId` to get the final description of `bookId` rendered like this?
```
Book identifier

UTF-8 string, max length 256 characters
```

Just an idea of the syntax
```
type: object
properties:
  bookId: 
    type: StringId
    description: |
        Book identifier
        <<StringId.description>>
```
Thanks in advance!
