### ISSUE TITLE
Support baseUriParameters

### ISSUE THREAD

**Issue by iki** [raml2html/raml2html#99]
Base URI Parameters can be specified on root level, and/or on resource level, or are required string parameters by default. See http://raml.org/spec.html#base-uri-and-baseuriparameters.

Because they can be overridden at resource level, it would make sense to display them as *Base URI Parameters* in the request parameters block on the API method pop-up.

**Comment by kevinrenskers** [comment]
Could you create an example raml file that would illustrate this problem?

**Comment by iki** [comment]
sure, for example:
```yaml
#%RAML 0.8
---
title: Test base URI parameters
version: v1

baseUri: https://sample-app-{env}.herokuapp.com/api/{version}
baseUriParameters:
  env:
    description: |
      Deployment environment.
    enum: [dev, qa, stage, try, prod]
    default: dev

/production-only:
  baseUriParameters:
    env:
      enum: [prod]
```
